language: node_js

os:
  - osx
  - linux

script:
  - git clone https://github.com/juj/emsdk.git
  - cd emsdk
  - ./emsdk update
  - ./emsdk install latest
  - ./emsdk activate latest
  - source ./emsdk_env.sh
  - git clone --depth=1 https://github.com/openFrameworks/openFrameworks.git
  - cd openFrameworks
  - scripts/emscripten/./download_libs.sh
  - cd examples/3d/3DPrimitivesExample
  - cp ../../../scripts/templates/emscripten/Makefile .
  - cp ../../../scripts/templates/emscripten/config.make .
  - emmake make