language: node_js

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js:
        - node

    - os: linux
      language: node_js
      node_js:
        - node
      addons:
        apt:
          # https://kripken.github.io/emscripten-site/docs/building_from_source/building_emscripten_from_source_on_linux.html
          packages:
            - g++-4.8
            - build-essential
            - cmake
            - python2.7
            - nodejs
            - git-core
            - default-jre


script:
  - git clone https://github.com/juj/emsdk.git
  - cd emsdk
  - ./emsdk update
  - ./emsdk install latest
  - ./emsdk activate latest
  - source ./emsdk_env.sh
  - git clone --depth=1 https://github.com/openFrameworks/openFrameworks.git
  - cd openFrameworks
  - scripts/emscripten/./download_libs.sh
  - cd examples/3d/3DPrimitivesExample
  - cp ../../../scripts/templates/emscripten/Makefile .
  - cp ../../../scripts/templates/emscripten/config.make .
  - emmake make